synpop: attr_a.csv attr_b.csv attr_c.csv micro_sample.csv
	python generate_synthetic_population_from_data.py

data:
	python generate_macrosample_and_data_files.py
# generates attr_a.csv attr_b.csv attr_c.csv micro_sample.csv
